version: 1.16.{build}.0
image: Visual Studio 2017
cache: c:\tools\vcpkg\installed\
install:
- cmd: git submodule -q update --init
- cmd: vcpkg integrate install
build_script:
- ps: .\build.ps1 -configuration release
artifacts:
- path: bin\**\*.exe
  name: VDX_x86_amd64
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true