version: 1.16.{build}.0
image: Visual Studio 2017
cache: C:\projects\vdx\packages
install:
- cmd: git submodule -q update --init
before_build:
- nuget restore
build_script:
- ps: .\build.ps1 -configuration release
artifacts:
- path: bin\**\*.exe
  name: VDX_x86_amd64
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true